language: node_js
node_js:
  - "10"
script:
- npm test
- npm run-script build
before_deploy:
  - git config --local user.name "Travis"
  - git config --local user.email "grzegorz.lipecki@gmail.com"
  - git checkout master
  - git remote add origin-token https://${GitHub_Token}@github.com/Consdata/tslint-config.git
  - npm version minor -m "[skip travis] version release"
  - git push origin-token master
deploy:
  skip_cleanup: true
  provider: npm
  email: grzegorz.lipecki@gmail.com
  api_key:
    secure: ${NPM_TOKEN}
  on:
    branch: master
