language: node_js
node_js:
  - "10"
script:
- npm test
before_deploy:
  - git config --local user.name "Travis"
  - git config --local user.email "grzegorz.lipecki@gmail.com"
  - git checkout master
  - git remote add origin-token https://${GitHub_Token}@github.com/Consdata/tslint-config.git
  - npm version minor -m "[skip travis] version release"
  - git push origin-token master
deploy:
  provider: npm
  email: grzegorz.lipecki@gmail.com
  api_key:
    secure: tE3aUeICpvvON8MF5dpt//eEVXzWM5pIp0uQo0paKjHNK4p6UCfurmtZT+Q4JoW4sBIpJY7klgf+YCOhzgIT1qPlgfRNu4vZeq3xRbTK64jJKeZwwAu07uQZT/CifY7PHx4Ol8bk+272Zf7QYovOUotmTEgZpWI3BGBL9Hm1GDgFV0Cv+x59XDITe3yINKp2M0GkO2AdrI30pvEr2HF16a3iBrC5M54O6wh3crcAykKcs+ZZ2qLeV5vsmrlvhmf90v8hVqIB7wBCnozAfxctP5hGOiqyUxcY6cMsHQEOXkmRmmmLUNgstq1cJJwkiOgDM+T/Z286ZWKLetvL0pxl/BZuVp7+PaS/uHEoXppBh5K2XTa/8AsF79HrLzD2WHgbkh3Iann0QTORGKlxFYztr/ZdLYxm6U/A0iRPBmiUx4en8+vnCiUQfGjooc+PIH9L46fV2CFQLFMm2MD88oS1njO4Bux1QB9Nb6J4P4TlCrx6f05Q0I96BudI4d4ZZqbz3+MmbsW2lfQa2l0JuD7yHHW+lY+MYjmcsohyirlRMK5eYHq486zBq9cfB+JaJt2beGjStHxW7AnRQnn/SZRf0Rw+LW8H7G8yIITxrp1y5Fb9uO7/RO/nHcyxRBJOGltYDRiqKOtFldkA0MhgPgz4LboqppARz63AP6QHtPL4O+g=
  on:
    branch: master
